version: '3'

services:
  aimasters.db:
    image: postgres:11.4-alpine
    container_name: aimasters.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: aimasters
      POSTGRES_DB: aimasters_db
    restart: always
    volumes:
      - ./aimasters-backend/src/main/resources/db/changelog/init/01_create_user.sql:/docker-entrypoint-initdb.d/01.sql:ro
#      - ./aimasters-backend/src/main/resources/db/changelog/init/02_create_db.sql:/docker-entrypoint-initdb.d/02.sql:ro
      - ./aimasters-backend/src/main/resources/db/changelog/init/03_create_schema.sql:/docker-entrypoint-initdb.d/03.sql:ro
      - ./aimasters-backend/src/main/resources/db/changelog/init/04_create_ext_schema.sql:/docker-entrypoint-initdb.d/04.sql:ro

  aimasters.backend:
    image: aimasters.backend
    container_name: aimasters.backend
    ports:
      - 8086:8086
    restart: always
    environment:
      aimasters_DB_HOST: aimasters.db
      aimasters_DB_PORT: 5432
      aimasters_DB_INSTANCE: aimasters_db
      aimasters_DB_SCHEMA: aimasters
      aimasters_DB_USER: master
      aimasters_DB_PASSWORD: bombaster
    build:
      context: ./backend
      dockerfile: Dockerfile
    links:
      - aimasters.db


