package ru.dungeon.aimasters.backend.dtos.chat;

import static ru.dungeon.aimasters.backend.utils.JsonUtils.fromJson;
import static ru.dungeon.aimasters.backend.utils.JsonUtils.toJson;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import ru.dungeon.aimasters.backend.dtos.chat.ChatMessageDto;

/**
 * A chat completion generated by OpenAI
 */
@Data
public class ChatCompletionChoice {

  /**
   * This index of this completion in the returned list.
   */
  Integer index;

  ChatMessageDto message;

  /**
   * The reason why GPT stopped generating, for example "length".
   */
  @JsonProperty("finish_reason")
  String finishReason;

  public MessageContent getMessageContent() {
    return fromJson(message.getContent(), MessageContent.class);
  }
}
